version: "3.9"

services:
  backend:
    container_name: nest-backend
    build:
      context: ./backend   # папка с Nest.js
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb  # добавляем зависимость от MongoDB

  frontend:
    container_name: phaser-frontend
    build:
      context: ./frontend   # папка с React/Phaser
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongodb:
    container_name: game-mongodb
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: game_data
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
  mongodb_config: