import { CraftItem } from "src/game/crafting.service";

export const itemsJson: CraftItem[] = [
  { "name": "wood", "title": "Дерево", "type": "resource" },
  { "name": "stone", "title": "Камень", "type": "resource" },
  { "name": "iron_ore", "title": "Железная руда", "type": "resource" },
  { "name": "copper_ore", "title": "Медная руда", "type": "resource" },
  { "name": "tin_ore", "title": "Оловянная руда", "type": "resource" },
  { "name": "sand", "title": "Песок", "type": "resource" },
  { "name": "clay", "title": "Глина", "type": "resource" },
  { "name": "fiber", "title": "Волокно", "type": "resource" },
  { "name": "cotton", "title": "Хлопок", "type": "resource" },
  { "name": "reed", "title": "Тростник", "type": "resource" },
  { "name": "hide", "title": "Шкура", "type": "resource" },
  { "name": "coal", "title": "Уголь", "type": "resource" },
  { "name": "gold_ore", "title": "Золотая руда", "type": "resource" },
  { "name": "salt", "title": "Соль", "type": "resource" },
  { "name": "herb", "title": "Трава", "type": "resource" },
  { "name": "plank", "title": "Доска", "type": "material" },
  { "name": "stick", "title": "Палка", "type": "material" },
  { "name": "rope", "title": "Верёвка", "type": "material" },
  { "name": "cloth", "title": "Ткань", "type": "material" },
  { "name": "leather", "title": "Кожа", "type": "material" },
  { "name": "iron_ingot", "title": "Железный слиток", "type": "material" },
  { "name": "bronze_ingot", "title": "Бронзовый слиток", "type": "material" },
  { "name": "gold_ingot", "title": "Золотой слиток", "type": "material" },
  { "name": "glass", "title": "Стекло", "type": "material" },
  { "name": "brick", "title": "Кирпич", "type": "material" },
  { "name": "paper", "title": "Бумага", "type": "material" },
  { "name": "bowstring", "title": "Тетива", "type": "material" },
  { "name": "sword", "title": "Меч", "type": "item" },
  { "name": "axe", "title": "Топор", "type": "item" },
  { "name": "bow", "title": "Лук", "type": "item" },
  { "name": "crossbow", "title": "Арбалет", "type": "item" },
  { "name": "shield", "title": "Щит", "type": "item" },
  { "name": "armor", "title": "Броня", "type": "item" },
  { "name": "helmet", "title": "Шлем", "type": "item" },
  { "name": "pickaxe", "title": "Кирка", "type": "item" },
  { "name": "hammer", "title": "Молоток", "type": "item" },
  { "name": "torch", "title": "Факел", "type": "item" },
  { "name": "lantern", "title": "Фонарь", "type": "item" },
  { "name": "furnace", "title": "Печь", "type": "item" },
  { "name": "anvil", "title": "Наковальня", "type": "item" },
  { "name": "bed", "title": "Кровать", "type": "item" },
  { "name": "table", "title": "Стол", "type": "item" },
  { "name": "chair", "title": "Стул", "type": "item" },
  { "name": "bottle", "title": "Бутылка", "type": "item" },
  { "name": "pottery", "title": "Горшок", "type": "item" },
  { "name": "book", "title": "Книга", "type": "item" },
  { "name": "map", "title": "Карта", "type": "item" },
  { "name": "ring", "title": "Кольцо", "type": "item" },
  { "name": "amulet", "title": "Амулет", "type": "item" },
  { "name": "potion", "title": "Зелье", "type": "item" },
  { "name": "bread", "title": "Хлеб", "type": "item" },
  { "name": "meat_stew", "title": "Мясное рагу", "type": "item" }
]
